/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.example

import spock.lang.Specification

class BowlingGameTest extends Specification {
    def "gutter game should have 0 score"() {
        setup:
        def game = new BowlingGame()

        when:
        def scorecard = [0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0] as int[]
        game.roll scorecard

        then:
        game.score == 0
    }

    def "all 1s game should have 20 score"() {
        setup:
        def game = new BowlingGame()

        when:
        def scorecard = [1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1, 1,1] as int[]
        game.roll scorecard

        then:
        game.score == 20
    }

    def "spare followed by 3 then all gutters should have 16 score"() {
        setup:
        def game = new BowlingGame()

        when:
        def scorecard = [5,5, 3,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0] as int[]
        game.roll scorecard

        then:
        game.score == 16
    }

    def "strike followed by 3,3 then all gutters should have 22 score"() {
        setup:
        def game = new BowlingGame()

        when:
        def scorecard = [10, 3,3, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0] as int[]
        game.roll scorecard

        then:
        game.score == 22
    }

    def "maximum score game should have 300 score"() {
        setup:
        def game = new BowlingGame()

        when:
        def scorecard = [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10] as int[]
        game.roll scorecard

        then:
        game.score == 300
    }
}
