/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class BowlingGame {
    private int[] scorecard = new int[21];
    private int rollNumber = 0;

    public void roll(int... pinsDown) {
        for(int i : pinsDown) {
            scorecard[rollNumber++] = i;
        }
    }

    public int getScore() {
        int sum = 0;

        for(int score : scorecard) {
            sum += score;
        }

        return sum;
    }
}
