/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class BowlingGame {
    public void roll(int... pinsDown) {

    }

    public int getScore() {
        return 0;
    }
}
